### ISSUE TITLE
"Enqueued to be updated 3 months ago"

### ISSUE THREAD

**Issue by KangOl** [hstove/issue_stats#14]
http://issuestats.com/github/odoo/odoo is stuck since 3 month?

Can you reset it?
Maybe you can add some timeout functionality and reset repositories taking too much time to fetch data...

**Comment by ForNeVeR** [comment]
Same here: www.issuestats.com/github/ForNeVeR/Tracktor

**Comment by jfallows** [comment]
Same here: http://www.issuestats.com/github/k3po/specification.wse

**Comment by nchammas** [comment]
@hstove Any update on the hung repos mentioned in this thread?

**Comment by hstove** [comment]
Thanks for the bug reports! Currently, if the 'refresh' background job fails, repositories get stuck in this limbo. I've added a link to 'refresh' the build again if an hour has passed since the report was last enqueued. There's more robust error handling I should do, but this quick fix allows the user to at least run the job again.

Go ahead and click 'refresh' at the bottom of the page for these repos and they will get re-ran. 

Thanks!

**Comment by nchammas** [comment]
@hstove

http://issuestats.com/github/apache/spark

This repo appears as "enqueued to be updated a minute ago" and has been like that for many weeks. Therefore, the refresh link you mentioned doesn't show up. 

Is there something else we can do to fix that repo?

**Comment by hstove** [comment]
That project was failing because it has issues disabled, and the report wouldn't get ran correctly. This has been fixed and reports will get ran for PRs even if issues are disabled. The page for Apache Spark is looking good now.

Thanks!

**Comment by nchammas** [comment]
Thank you!

**Comment by hstove** [comment]
I've checked all reported repositories and they're all functioning well. Thanks for the reports, and sorry it took so long!
